Initial commit with previous reverted changes.

diff --git a/circleci/catapult-publish b/circleci/catapult-publish
--- a/circleci/catapult-publish
+++ b/circleci/catapult-publish
@@ -27,6 +27,7 @@ CATAPULT_PASS=$3
 if [[ -z $CATAPULT_PASS ]]; then echo "Missing arg3 CATAPULT_PASS" && exit 1; fi
 APP_NAME=$4
 if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
+if [[ -z $GH_RELEASE_TOKEN ]]; then echo "Missing GH_RELEASE_TOKEN" && exit 1; fi
 
 # Set automatically by CircleCI
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
@@ -38,7 +39,7 @@ BUILD_NUM=$CIRCLE_BUILD_NUM
 : ${CIRCLE_BRANCH?"Missing required env var"}
 BRANCH=$CIRCLE_BRANCH
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
-REPO=$CIRCLE_PROJECT_REPONAME
+REPO_NAME=$CIRCLE_PROJECT_REPONAME
 : ${CIRCLE_SHA1?"Missing required env var"}
 SHORT_SHA=${CIRCLE_SHA1:0:7}
 FULL_SHA=${CIRCLE_SHA1}
@@ -56,7 +57,7 @@ fi
 
 echo "Publishing to catapult..."
 echo "Using data:"
-DATA="{\"username\":\"${USER}\",\"reponame\":\"${REPO}\",\"buildnum\":${BUILD_NUM},\"app\":{\"run_type\":\"${RUN_TYPE}\",\"id\":\"${APP_NAME}\",\"source\":\"github:Clever/${REPO}@${FULL_SHA}\",\"branch\":\"${BRANCH}\",\"artifacts\":\"docker:clever/$REPO@$SHORT_SHA\"}}"
+DATA="{\"username\":\"${USER}\",\"reponame\":\"${REPO_NAME}\",\"buildnum\":${BUILD_NUM},\"app\":{\"run_type\":\"${RUN_TYPE}\",\"id\":\"${APP_NAME}\",\"source\":\"github:Clever/${REPO_NAME}@${FULL_SHA}\",\"branch\":\"${BRANCH}\",\"artifacts\":\"docker:clever/$REPO_NAME@$SHORT_SHA\"}}"
 echo "${DATA}"
 echo "================================================================================"
 SC=$(curl -u $CATAPULT_USER:$CATAPULT_PASS \
