reduce usage of GH_RELEASE_TOKEN where it isnt present

diff --git a/circleci/catapult-publish b/circleci/catapult-publish
--- a/circleci/catapult-publish
+++ b/circleci/catapult-publish
@@ -27,7 +27,6 @@ CATAPULT_PASS=$3
 if [[ -z $CATAPULT_PASS ]]; then echo "Missing arg3 CATAPULT_PASS" && exit 1; fi
 APP_NAME=$4
 if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
-if [[ -z $GH_RELEASE_TOKEN ]]; then echo "Missing GH_RELEASE_TOKEN" && exit 1; fi
 
 # Set automatically by CircleCI
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
@@ -44,37 +43,43 @@ REPO_NAME=$CIRCLE_PROJECT_REPONAME
 SHORT_SHA=${CIRCLE_SHA1:0:7}
 FULL_SHA=${CIRCLE_SHA1}
 
-. $DIR/install-goci
+# If file go.mod exists
+if [ -f go.mod ]; then
+  . $DIR/install-goci
 
-set +e
-echo "Running goci..."
+  set +e
+  echo "Running goci..."
 
-VALIDATE_OUTPUT=$(goci validate)
-GOCI_EXIT_CODE=$?
+  VALIDATE_OUTPUT=$(goci validate)
+  GOCI_EXIT_CODE=$?
 
 
-if [[ $GOCI_EXIT_CODE -eq 2 ]]; then
-  echo "goci failed with exit code $GOCI_EXIT_CODE"
-  echo "$VALIDATE_OUTPUT"
-  post_github_pr_comment $USER $REPO_NAME $FULL_SHA $GH_RELEASE_TOKEN "$VALIDATE_OUTPUT"
-  exit $GOCI_EXIT_CODE
-elif [[ $GOCI_EXIT_CODE -eq 1 ]]; then
-  echo "goci failed with exit code $GOCI_EXIT_CODE"
-  echo "$VALIDATE_OUTPUT"
-  exit $GOCI_EXIT_CODE
+  if [[ $GOCI_EXIT_CODE -eq 2 ]]; then
+    if [[ -z $GH_RELEASE_TOKEN ]]; then echo "Missing GH_RELEASE_TOKEN" && exit 1; fi
+    echo "goci failed with exit code $GOCI_EXIT_CODE"
+    echo "$VALIDATE_OUTPUT"
+    post_github_pr_comment $USER $REPO_NAME $FULL_SHA $GH_RELEASE_TOKEN "$VALIDATE_OUTPUT"
+    exit $GOCI_EXIT_CODE
+  elif [[ $GOCI_EXIT_CODE -eq 1 ]]; then
+    echo "goci failed with exit code $GOCI_EXIT_CODE"
+    echo "$VALIDATE_OUTPUT"
+    exit $GOCI_EXIT_CODE
+  fi
+
+  set -e
+
+  # If a warning is present for a go based repo, we print the warning and will make a PR comment with the warning message
+  if [[ -n "$VALIDATE_OUTPUT"  ]]; then
+    echo "goci warning:"
+    echo "$VALIDATE_OUTPUT"
+
+    post_github_pr_comment $USER $REPO_NAME $FULL_SHA $GH_RELEASE_TOKEN "$VALIDATE_OUTPUT"
+  fi
+
+  echo "goci passed."
+else
+  echo "No go.mod file found. Skipping goci."
 fi
-
-set -e
-
-# If a warning is present for a go based repo, we print the warning and will make a PR comment with the warning message
-if [[ -n "$VALIDATE_OUTPUT"  ]]; then
-  echo "goci warning:"
-  echo "$VALIDATE_OUTPUT"
-
-  post_github_pr_comment $USER $REPO_NAME $FULL_SHA $GH_RELEASE_TOKEN "$VALIDATE_OUTPUT"
-fi
-
-echo "goci passed."
 
 install_yq
 
