Initial commit, now using goci within the catapult publish script.

diff --git a/circleci/catapult-publish b/circleci/catapult-publish
--- a/circleci/catapult-publish
+++ b/circleci/catapult-publish
@@ -28,6 +28,8 @@ if [[ -z $CATAPULT_PASS ]]; then echo "Missing arg3 CATAPULT_PASS" && exit 1; fi
 APP_NAME=$4
 if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
 
+if [[ -z $GH_RELEASE_TOKEN ]]; then echo "Missing var GH_RELEASE_TOKEN" && exit 1; fi
+
 # Set automatically by CircleCI
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
 REPO=$CIRCLE_PROJECT_REPONAME
@@ -42,6 +44,33 @@ REPO=$CIRCLE_PROJECT_REPONAME
 : ${CIRCLE_SHA1?"Missing required env var"}
 SHORT_SHA=${CIRCLE_SHA1:0:7}
 FULL_SHA=${CIRCLE_SHA1}
+
+./install_goci
+
+# Run the validate step using goci and capture the output
+VALIDATE_OUTPUT=$(goci artifact-build-publish-deploy)
+VALIDATE_EXIT_CODE=$?
+
+# In the case of an error - we print the error and will make a PR comment with the error message
+if [[ $VALIDATE_EXIT_CODE -ne 0 ]]; then
+  echo "goci failed with the following output:"
+  echo "$VALIDATE_OUTPUT"
+
+  post_github_pr_comment $USER $REPO $FULL_SHA $GH_RELEASE_TOKEN $VALIDATE_OUTPUT
+  
+  exit 1
+fi
+
+# If a warning is present, we print the warning and will make a PR comment with the warning message
+if [[ -n "$VALIDATE_OUTPUT" ]]; then
+  echo "goci output:"
+  echo "$VALIDATE_OUTPUT"
+
+  post_github_pr_comment $USER $REPO $FULL_SHA $GH_RELEASE_TOKEN $VALIDATE_OUTPUT
+
+  exit 0
+fi
+
 
 install_yq
 
