remove zip arg

diff --git a/circleci/catapult-publish-lambda b/circleci/catapult-publish-lambda
--- a/circleci/catapult-publish-lambda
+++ b/circleci/catapult-publish-lambda
@@ -4,15 +4,13 @@
 #
 # Usage:
 #
-#   catapult-publish-lambda [ZIP FILE] [APP NAME]
+#   catapult-publish-lambda [APP NAME]
 
 set -e
 
 # User supplied arg
-ZIP_FILE=$1
-if [[ -z $ZIP_FILE ]]; then echo "Missing arg1 ZIP_FILE" && exit 1; fi
-APP_NAME=$2
-if [[ -z $APP_NAME ]]; then echo "Missing arg2 APP_NAME" && exit 1; fi
+APP_NAME=$1
+if [[ -z $APP_NAME ]]; then echo "Missing arg1 APP_NAME" && exit 1; fi
 
 RUN_TYPE=$(grep type launch/${APP_NAME}.yml | cut -d' ' -f4)
 AWS_REGION=$(echo ${RUN_TYPE} | cut -d'/' -f2)
@@ -49,7 +47,7 @@ echo "Uploading to S3..."
 AWS_REGION=$AWS_REGION \
           AWS_ACCESS_KEY_ID=$LAMBDA_AWS_ACCESS_KEY_ID \
           AWS_SECRET_ACCESS_KEY=$LAMBDA_AWS_SECRET_ACCESS_KEY \
-          aws s3 cp ${ZIP_FILE} s3://${LAMBDA_AWS_BUCKET}-${AWS_REGION}/${LAMBDA_AWS_S3_KEY}
+          aws s3 cp bin/${APP_NAME}.zip s3://${LAMBDA_AWS_BUCKET}-${AWS_REGION}/${LAMBDA_AWS_S3_KEY}
 
 # publish the application to catapult
 echo "Publishing to catapult..."
