updates.

diff --git a/circleci/catapult-publish b/circleci/catapult-publish
--- a/circleci/catapult-publish
+++ b/circleci/catapult-publish
@@ -28,6 +28,8 @@ if [[ -z $CATAPULT_PASS ]]; then echo "Missing arg3 CATAPULT_PASS" && exit 1; fi
 APP_NAME=$4
 if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
 
+if [[ -z $GH_RELEASE_TOKEN ]]; then echo "Missing GH_RELEASE_TOKEN" && exit 1; fi
+
 # Set automatically by CircleCI
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
 REPO=$CIRCLE_PROJECT_REPONAME
