remove region from args

diff --git a/circleci/catapult-publish-lambda b/circleci/catapult-publish-lambda
--- a/circleci/catapult-publish-lambda
+++ b/circleci/catapult-publish-lambda
@@ -4,15 +4,13 @@
 #
 # Usage:
 #
-#   catapult-publish-lambda [AWS REGION] [APP NAME]
+#   catapult-publish-lambda [APP NAME]
 
 set -e
 
 # User supplied arg
-LAMBDA_AWS_REGION=$1
-if [[ -z $LAMBDA_AWS_REGION ]]; then echo "Missing arg1 REGION" && exit 1; fi
-APP_NAME=$2
-if [[ -z $APP_NAME ]]; then echo "Missing arg2 APP_NAME" && exit 1; fi
+APP_NAME=$1
+if [[ -z $APP_NAME ]]; then echo "Missing arg1 APP_NAME" && exit 1; fi
 
 # Set automatically by CircleCI
 : ${CIRCLE_PROJECT_REPONAME?"Missing required env var"}
@@ -42,7 +40,7 @@ LAMBDA_AWS_S3_KEY=${REPO}/${SHORT_SHA}/handler.zip
 
 # upload to s3
 echo "Uploading to S3..."
-AWS_REGION=$LAMBDA_AWS_REGION \
+AWS_REGION=us-west-2 \ # region doesn't really matter for an S3 upload, since the bucket region is fixed
           AWS_ACCESS_KEY_ID=$LAMBDA_AWS_ACCESS_KEY_ID \
           AWS_SECRET_ACCESS_KEY=$LAMBDA_AWS_SECRET_ACCESS_KEY \
           aws s3 cp bin/handler.zip s3://${LAMBDA_AWS_BUCKET}/${LAMBDA_AWS_S3_KEY}
@@ -54,7 +52,7 @@ SC=$(curl -u $CATAPULT_USER:$CATAPULT_PASS \
           --output catapult.out \
           -H "Content-Type: application/json" \
           -X POST \
-          -d "{\"username\":\"${USER}\",\"reponame\":\"${REPO}\",\"buildnum\":${BUILD_NUM},\"app\":{\"run_type\":\"lambda\",\"id\":\"${APP_NAME}\",\"source\":\"github:Clever/${REPO}@${FULL_SHA}\",\"artifacts\":\"lambda:clever/${REPO}@${SHORT_SHA};Region=\\\"${LAMBDA_AWS_REGION},S3Bucket=\\\"${LAMBDA_AWS_BUCKET},S3Key=\\\"${LAMBDA_AWS_S3_KEY}\",\"branch\":\"${BRANCH}\"}}" \
+          -d "{\"username\":\"${USER}\",\"reponame\":\"${REPO}\",\"buildnum\":${BUILD_NUM},\"app\":{\"run_type\":\"lambda\",\"id\":\"${APP_NAME}\",\"source\":\"github:Clever/${REPO}@${FULL_SHA}\",\"artifacts\":\"lambda:clever/${REPO}@${SHORT_SHA};S3Bucket=\\\"${LAMBDA_AWS_BUCKET},S3Key=\\\"${LAMBDA_AWS_S3_KEY}\",\"branch\":\"${BRANCH}\"}}" \
           $CATAPULT_URL)
 
 if [ "$SC" -eq 200 ]; then
