make url name more descriptive

diff --git a/circleci/catalog-sync b/circleci/catalog-sync
--- a/circleci/catalog-sync
+++ b/circleci/catalog-sync
@@ -5,14 +5,14 @@
 #
 # Usage:
 #
-#   catalog-sync [URL] [USER] [PASS] [APP_NAME]
+#   catalog-sync [CIRCLE_CI_INTEGRATIONS_URL] [USER] [PASS] [APP_NAME]
 #
 
 set -e
 
 # User supplied args
 URL=$1
-if [[ -z $URL ]]; then echo "Missing arg1 URL" && exit 1; fi
+if [[ -z $CIRCLE_CI_INTEGRATIONS_URL ]]; then echo "Missing arg1 CIRCLE_CI_INTEGRATIONS_URL" && exit 1; fi
 USER=$2
 if [[ -z $USER ]]; then echo "Missing arg2 USER" && exit 1; fi
 PASS=$3
@@ -21,12 +21,12 @@ APP_NAME=$4
 if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
 
 echo "Posting to catalog sync service..."
-SC=$(curl -u $USER:$PASS \
+SC=$(curl -u $CIRCLE_CI_INTEGRATIONS_URL:$PASS \
   --retry 5 \
   -w "%{http_code}" \
   -H "Content-Type: application/json" \
   -X POST \
-  $URL/serviceCatalog?app=$APP_NAME)
+  $CIRCLE_CI_INTEGRATIONS_URL/serviceCatalog?app=$APP_NAME)
 
 if [ "$SC" -eq 200 ]; then
   echo "Successfully published app catalog config"
