Infrang 7446 (#178)
* update goci and ci-scripts to use entity endpoint only

and delete unused scripts

* fix url parsing by adding quotes

diff --git a/circleci/catalog-sync b/circleci/catalog-sync
--- a/circleci/catalog-sync
+++ b/circleci/catalog-sync
@@ -5,7 +5,7 @@
 #
 # Usage:
 #
-#   catalog-sync [CIRCLE_CI_INTEGRATIONS_URL] [USER] [PASS] [APP_NAME]
+#   catalog-sync [CIRCLE_CI_INTEGRATIONS_URL] [USER] [PASS] [ENTITY_NAME] [TYPE]
 #
 
 set -e
@@ -24,8 +24,10 @@ USER=$2
 if [[ -z $USER ]]; then echo "Missing arg2 USER" && exit 1; fi
 PASS=$3
 if [[ -z $PASS ]]; then echo "Missing arg3 PASS" && exit 1; fi
-APP_NAME=$4
-if [[ -z $APP_NAME ]]; then echo "Missing arg4 APP_NAME" && exit 1; fi
+ENTITY_NAME=$4
+if [[ -z $ENTITY_NAME ]]; then echo "Missing arg4 ENTITY_NAME" && exit 1; fi
+TYPE=$5
+if [[ -z $TYPE ]]; then echo "Missing arg5 TYPE" && exit 1; fi
 
 echo "Posting to catalog sync service..."
 SC=$(curl -u $USER:$PASS \
@@ -33,7 +35,7 @@ SC=$(curl -u $USER:$PASS \
   -w "%{http_code}" \
   -H "Content-Type: application/json" \
   -X POST \
-  $CIRCLE_CI_INTEGRATIONS_URL/serviceCatalog?app=$APP_NAME)
+  "$CIRCLE_CI_INTEGRATIONS_URL/catalogEntity?entity=$ENTITY_NAME&type=$TYPE")
 
 if [ "$SC" -eq 200 ]; then
   echo "Successfully published app catalog config"
