Update check-make-generate (#79)
* Update check-make-generate to:

1. Check for newly created files in addition to modified files
2. Ignore files modified earlier in the CircleCI build process

* Remove default FILES_TO_IGNORE and specify via command line

The default FILES_TO_IGNORE can all be addressed via other means,
specifically .gitignore updates and CircleCI command updates

diff --git a/circleci/check-make-generate b/circleci/check-make-generate
--- a/circleci/check-make-generate
+++ b/circleci/check-make-generate
@@ -4,25 +4,50 @@
 #
 # Usage:
 #
-#   check-make-generate
+#   check-make-generate --files-to-ignore file1,file2,...,fileN
 
 set -e
 
-USAGE="Usage: check-make-generate"
+USAGE="Usage: check-make-generate --files-to-ignore file1,file2,...,fileN"
 
-if [[ "$#" -ne 0 ]]; then
+if [[ "$#" -ne 0 && "$#" -ne 2 ]]; then
   echo "$USAGE"
   exit 1
+fi
+
+declare -a FILES_TO_IGNORE
+if [[ "$#" -eq 2 ]]; then
+  if [[ "$1" != "--files-to-ignore" ]]; then
+    echo "$USAGE"
+    exit 1
+  fi
+  IFS="," read -a FILES_TO_IGNORE <<< "$2"
 fi
 
 echo "Running 'make generate' and checking for diffs..."
 
 make generate > /dev/null
 
-if git diff --quiet --exit-code; then
+# 'git status --porcelain' lists modified files as well as untracked (i.e. newly created) files in
+# a format that is guaranteed to be consistent, making the command ideal for scripting. File names
+# always begin at the fourth character of each line, hence the 'cut -c 4-'.
+diffFiles=$(git status --porcelain | cut -c 4-)
+for fileToIgnore in "${FILES_TO_IGNORE[@]}"; do
+  # Remove each fileToIgnore from the list. Use -F and -x to perform exact line matching rather
+  # than regex matching. Add an '|| echo ""' fallback because grep returns with an error when no
+  # lines are matched, causing the script to fail without the fallback.
+  diffFiles=$(echo "$diffFiles" | grep -Fvx "$fileToIgnore" || echo "")
+done
+
+if [[ -n "$diffFiles" ]]; then
+  echo ""
+  echo "Found diffs involving the following files:"
+  echo ""
+  echo "$diffFiles"
+  echo ""
+  echo "Please run 'make generate'."
+  exit 1
+else
   echo "Found no diffs. 'make generate' has been run."
   exit 0
-else
-  echo "Found diffs. Please run 'make generate'."
-  exit 1
 fi
