update docker-publish to work with OIDC based aws authentication

diff --git a/circleci/docker-publish b/circleci/docker-publish
--- a/circleci/docker-publish
+++ b/circleci/docker-publish
@@ -7,7 +7,7 @@
 #
 #   docker-publish 
 #   optional flag "-r private-repos" enables Docker Build Kit to allow ssh socket mounting to pull private modules/repos
-
+#   optional flag "-p profile" uses `profile` to authenticate into AWS without using the hardcoded env vars ECR_ACCOUNT_ID and ECR_PUSH_SECRET
 
 set -e
 
@@ -25,9 +25,10 @@ else
 fi
 
 readopt='none'
-while getopts 'r:' flag; do
+while getopts ':r:p:' flag; do
     case "${flag}" in
         r) readopt=${OPTARG};;
+        p) profile=${OPTARG};;
     esac
 done
 
@@ -43,14 +44,24 @@ image_exists() {
 
 check_ecr_vars() {
   # ECR required env vars
-  if [[ -z $ECR_ACCOUNT_ID ]]; then echo "Missing var for ECR: ECR_ACCOUNT_ID" && exit 1; fi
-  if [[ -z $ECR_PUSH_SECRET ]]; then echo "Missing var for ECR: ECR_PUSH_SECRET" && exit 1; fi
+  if [[ -z $profile ]]; then
+    if [[ -z $ECR_ACCOUNT_ID ]]; then echo "Missing var for ECR: ECR_ACCOUNT_ID" && exit 1; fi
+    if [[ -z $ECR_PUSH_SECRET ]]; then echo "Missing var for ECR: ECR_PUSH_SECRET" && exit 1; fi
+  else
+    echo "Using AWS profile '${profile}' to login to aws ecr"
+  fi
 }
 
 ecr_login(){
   REGION=$1
   ECR_REPO=$ECR_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
   AWS_ACCESS_KEY_ID=$2 AWS_SECRET_ACCESS_KEY=$3 aws ecr --region $REGION get-login-password | docker login --username AWS --password-stdin $ECR_REPO
+}
+
+ecr_login_with_profile(){
+  REGION=$1
+  ECR_REPO=$ECR_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
+  aws ecr --region $REGION get-login-password --profile $2 | docker login --username AWS --password-stdin $ECR_REPO
 }
 
 push_ecr_image(){
@@ -102,10 +113,17 @@ fi
 
 # ECR login.
 echo "Logging into ECR..."
-ecr_login $ECR_REGION_US_WEST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
-ecr_login $ECR_REGION_US_WEST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
-ecr_login $ECR_REGION_US_EAST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
-ecr_login $ECR_REGION_US_EAST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
+if [[ -z $profile ]]; then
+  ecr_login $ECR_REGION_US_WEST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
+  ecr_login $ECR_REGION_US_WEST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
+  ecr_login $ECR_REGION_US_EAST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
+  ecr_login $ECR_REGION_US_EAST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
+else
+  ecr_login_with_profile $ECR_REGION_US_WEST_1 $profile
+  ecr_login_with_profile $ECR_REGION_US_WEST_2 $profile
+  ecr_login_with_profile $ECR_REGION_US_EAST_1 $profile
+  ecr_login_with_profile $ECR_REGION_US_EAST_2 $profile
+fi
 
 echo "Pushing to ECR..."
 push_ecr_image $ECR_REGION_US_WEST_1
