Update docker-publish to be relying on context defined ENV vars for role based auth

diff --git a/circleci/docker-publish b/circleci/docker-publish
--- a/circleci/docker-publish
+++ b/circleci/docker-publish
@@ -7,7 +7,6 @@
 #
 #   docker-publish 
 #   optional flag "-r private-repos" enables Docker Build Kit to allow ssh socket mounting to pull private modules/repos
-#   optional flag "-p profile" uses `profile` to authenticate into AWS without using the hardcoded env vars ECR_ACCOUNT_ID and ECR_PUSH_SECRET
 
 set -e
 
@@ -25,10 +24,9 @@ else
 fi
 
 readopt='none'
-while getopts ':r:p:' flag; do
+while getopts ':r' flag; do
     case "${flag}" in
         r) readopt=${OPTARG};;
-        p) profile=${OPTARG};;
     esac
 done
 
@@ -43,12 +41,20 @@ image_exists() {
 }
 
 check_ecr_vars() {
-  # ECR required env vars
-  if [[ -z $profile ]]; then
+  # ECR required env vars. If CIRCLE_OIDC_TOKEN_V2 is defined via context, then use it to login to aws. 
+  if [[ -z $CIRCLE_OIDC_TOKEN_V2 ]]; then
     if [[ -z $ECR_ACCOUNT_ID ]]; then echo "Missing var for ECR: ECR_ACCOUNT_ID" && exit 1; fi
     if [[ -z $ECR_PUSH_SECRET ]]; then echo "Missing var for ECR: ECR_PUSH_SECRET" && exit 1; fi
   else
-    echo "Using AWS profile '${profile}' to login to aws ecr"
+    if [ -z "${OIDC_ECR_UPLOAD_ROLE}" ]; then
+      echo "Role name is required when using CIRCLE_OIDC_TOKEN_V2 to login to aws."
+      exit 1
+    fi
+    if [ -z "${CIRCLE_OIDC_TOKEN_V2}" ]; then
+      echo "OIDC Token cannot be found. A CircleCI context must be specified."
+      exit 1
+    fi
+    echo "Using AWS role '${OIDC_ECR_UPLOAD_ROLE}' to login to aws ecr"
   fi
 }
 
@@ -61,7 +67,7 @@ ecr_login(){
 ecr_login_with_profile(){
   REGION=$1
   ECR_REPO=$ECR_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
-  aws ecr --region $REGION get-login-password --profile $2 | docker login --username AWS --password-stdin $ECR_REPO
+  aws ecr --region $REGION get-login-password --profile $AWS_ECR_PROFILE | docker login --username AWS --password-stdin $ECR_REPO
 }
 
 push_ecr_image(){
@@ -87,6 +93,7 @@ ECR_REGION_US_WEST_1=us-west-1
 ECR_REGION_US_WEST_2=us-west-2
 ECR_REGION_US_EAST_1=us-east-1
 ECR_REGION_US_EAST_2=us-east-2
+AWS_ECR_PROFILE=oidc-ecr-profile
 
 echo "Docker version..."
 docker version
@@ -112,17 +119,19 @@ else
 fi
 
 # ECR login.
-echo "Logging into ECR..."
-if [[ -z $profile ]]; then
+if [[ -z $CIRCLE_OIDC_TOKEN_V2 ]]; then
+  echo "Logging into ECR using static credentials..."
   ecr_login $ECR_REGION_US_WEST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
   ecr_login $ECR_REGION_US_WEST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
   ecr_login $ECR_REGION_US_EAST_1 $ECR_PUSH_ID $ECR_PUSH_SECRET
   ecr_login $ECR_REGION_US_EAST_2 $ECR_PUSH_ID $ECR_PUSH_SECRET
 else
-  ecr_login_with_profile $ECR_REGION_US_WEST_1 $profile
-  ecr_login_with_profile $ECR_REGION_US_WEST_2 $profile
-  ecr_login_with_profile $ECR_REGION_US_EAST_1 $profile
-  ecr_login_with_profile $ECR_REGION_US_EAST_2 $profile
+  echo "Logging into ECR using role credentials..."
+  assume_role_with_web_identity $OIDC_ECR_UPLOAD_ROLE $AWS_ECR_PROFILE 
+  ecr_login_with_profile $ECR_REGION_US_WEST_1
+  ecr_login_with_profile $ECR_REGION_US_WEST_2
+  ecr_login_with_profile $ECR_REGION_US_EAST_1
+  ecr_login_with_profile $ECR_REGION_US_EAST_2
 fi
 
 echo "Pushing to ECR..."
diff --git a/circleci/utils b/circleci/utils
--- a/circleci/utils
+++ b/circleci/utils
@@ -21,6 +21,29 @@ install_awscli(){
   echo "Completed AWS cli install"
 }
 
+assume_role_with_web_identity() {
+  echo "Setting aws profile to $2"
+  aws configure set profile $2
+  echo "Authenticating via role $1..."
+  aws sts assume-role-with-web-identity \
+    --role-arn "$1" \
+    --role-session-name "oidc-ecr-role-session" \
+    --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
+    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
+    --output text > /tmp/cred.txt
+  read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN < /tmp/cred.txt 
+  
+  if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
+    echo "Failed to assume role";
+    exit 1
+  else
+    aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID} --profile $2
+    aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY} --profile $2
+    aws configure set aws_session_token ${AWS_SESSION_TOKEN} --profile $2
+    echo "Assume role with web identity succeeded."
+  fi
+}
+
 install_yq(){
   if type yq > /dev/null; then
     echo "yq already installed"
