check that all vars are set

diff --git a/circleci/docker-publish b/circleci/docker-publish
--- a/circleci/docker-publish
+++ b/circleci/docker-publish
@@ -11,6 +11,13 @@
 
 set -e
 
+check_ecr_vars() {
+  # ECR required env vars
+  if [[ -z $AWS_ACCOUNT_ID ]]; then echo "Missing var for ECR: AWS_ACCOUNT_ID" && exit 1; fi
+  if [[ -z $AWS_REGION ]]; then echo "Missing var for ECR: AWS_REGION" && exit 1; fi
+  if [[ -z $ECR_PUSH_SECRET ]]; then echo "Missing var for ECR: ECR_PUSH_SECRET" && exit 1; fi
+}
+
 push_ecr_image(){
 	eval $(AWS_ACCESS_KEY_ID=$ECR_PUSH_ID AWS_SECRET_ACCESS_KEY=$ECR_PUSH_SECRET aws ecr --region $AWS_REGION get-login)
 	docker tag $ORG/$REPO:$SHORT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO:$SHORT_SHA
@@ -37,7 +44,8 @@ echo "Building docker image..."
 docker build -t $ORG/$REPO:$SHORT_SHA .
 
 if [ $ECR_PUSH_ID != "" ]; then
-  echo "ECR credentials available. Pushing to ECR..."
+  echo "ECR access_id available. Pushing to ECR..."
+  check_ecr_vars
   push_ecr_image
 fi
 
