add user input github token

diff --git a/circleci/install-goci b/circleci/install-goci
--- a/circleci/install-goci
+++ b/circleci/install-goci
@@ -5,6 +5,9 @@
 # Exit immediately if a command exits with a non-zero status
 set -e
 
+GITHUB_TOKEN=$1
+if [[ -z $GITHUB_TOKEN ]]; then echo "Missing arg1 GITHUB_TOKEN" && exit 1; fi
+
 # Configuration
 REPO="Clever/ci-scripts"
 INSTALL_DIR="/usr/local/bin"
@@ -18,7 +21,7 @@ echo "Fetching the latest release from $REPO..."
 LATEST_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/releases/latest")
 
 if [ -z "$ASSET_URL" ]; then
-  echo "Error: No latest release found."
+  echo "Error: No latest release found. Check repository permissions."
   exit 1
 fi
 
