hardcode jobid to test

diff --git a/circleci/integration-test b/circleci/integration-test
--- a/circleci/integration-test
+++ b/circleci/integration-test
@@ -55,28 +55,28 @@ APPS=$(echo "${APP_NAMES}" |
     )
 
 echo "Submitting to integration-testing-service..."
-SC=$(curl -u $TESTING_SERVICE_USER:$TESTING_SERVICE_PASS \
-  -w "%{http_code}" \
-  --output integration-tests.out \
-  -H "Content-Type: application/json" \
-  -X POST \
-  -d "{\"username\":\"$USER\",\"reponame\":\"$REPO\",\"buildnum\":$BUILD_NUM,\"apps\":${APPS},\"tests\":${TESTS_TO_RUN}}" \
-  $TESTING_SERVICE_URL)
+# SC=$(curl -u $TESTING_SERVICE_USER:$TESTING_SERVICE_PASS \
+#   -w "%{http_code}" \
+#   --output integration-tests.out \
+#   -H "Content-Type: application/json" \
+#   -X POST \
+#   -d "{\"username\":\"$USER\",\"reponame\":\"$REPO\",\"buildnum\":$BUILD_NUM,\"apps\":${APPS},\"tests\":${TESTS_TO_RUN}}" \
+#   $TESTING_SERVICE_URL)
 
-if [[ $SC -eq 200 ]]; then
-  echo "Successfully submitted to integration-testing-service"
-  JOB_ID=$(cat integration-tests.out | jq -r '.jobId')
-  rm -f integration-tests.out
-else
-  echo "Failed to submit tests to integration-testing-service"
-  echo "------------------------------------------------"
-  cat integration-tests.out
-  echo ""
-  echo "------------------------------------------------"
-  rm -f integration-tests.out
-  exit 1
-fi
-
+# if [[ $SC -eq 200 ]]; then
+#   echo "Successfully submitted to integration-testing-service"
+#   JOB_ID=$(cat integration-tests.out | jq -r '.jobId')
+#   rm -f integration-tests.out
+# else
+#   echo "Failed to submit tests to integration-testing-service"
+#   echo "------------------------------------------------"
+#   cat integration-tests.out
+#   echo ""
+#   echo "------------------------------------------------"
+#   rm -f integration-tests.out
+#   exit 1
+# fi
+JOB_ID="ba147bda-894a-4ad0-b2f1-9c53fc547cd7"
 echo "Job ID: $JOB_ID"
 
 install_awscli
