Update report card to track return codes

diff --git a/circleci/report-card b/circleci/report-card
--- a/circleci/report-card
+++ b/circleci/report-card
@@ -7,8 +7,6 @@
 #   report-card [DOCKER_USER] [DOCKER_PASS] [DOCKER_EMAIL] [GITHUB_TOKEN]
 #
 
-set -e
-
 if [ $# -ne 4 ]; then
     echo "Incorrect number of arguments given. Expected 4, received $#"
     echo "Usage: report-card [DOCKER_USER] [DOCKER_PASS] [DOCKER_EMAIL] [GITHUB_TOKEN]"
@@ -26,17 +24,22 @@ REPORT_CARD_IMAGE="1a90b84"
 
 echo "Logging into DockerHub..."
 docker login -u $DOCKER_USER -p $DOCKER_PASS --email="$DOCKER_EMAIL"
+if [ $? -ne 0 ]; then
+    echo "ERROR: Failed to login to dockerhub"
+    exit 1
+fi
 
 echo "Pulling report-card:$REPORT_CARD_IMAGE ..."
 timeout 5m docker pull clever/report-card:$REPORT_CARD_IMAGE
 if [ $? -ne 0 ]; then
     echo "ERROR: Timed out while pulling report-card image. A rebuild should fix this."
     exit 1
-else
-    echo "Running report-card..."
-    docker run -t \
-        -v `pwd`:/repo/$(basename `pwd`) \
-        -e GITHUB_API_TOKEN=$GITHUB_TOKEN \
-        clever/report-card:$REPORT_CARD_IMAGE \
-        --repo /repo/$(basename `pwd`) --publish
 fi
+
+echo "Running report-card..."
+docker run -t \
+    -v `pwd`:/repo/$(basename `pwd`) \
+    -e GITHUB_API_TOKEN=$GITHUB_TOKEN \
+    clever/report-card:$REPORT_CARD_IMAGE \
+    --repo /repo/$(basename `pwd`) --publish
+exit $?
