report-card validation

diff --git a/circleci-report-card b/circleci-report-card
--- a/circleci-report-card
+++ b/circleci-report-card
@@ -2,9 +2,13 @@
 
 set -e
 
-DOCKERHUB_USER=$1
-DOCKERHUB_PASS=$2
-DOCKERHUB_EMAIL=$3
+# User supplied args
+DOCKER_USER=$1
+if [[ -z $DOCKER_USER ]]; then echo "Missing arg1 DOCKER_USER" && exit 1; fi
+DOCKER_PASS=$2
+if [[ -z $DOCKER_PASS ]]; then echo "Missing arg2 DOCKER_PASS" && exit 1; fi
+DOCKER_EMAIL=$3
+if [[ -z $DOCKER_EMAIL ]]; then echo "Missing arg3 DOCKER_EMAIL" && exit 1; fi
 
 echo "Logging into DockerHub..."
 docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS --email="$DOCKERHUB_EMAIL"
